(UPDATE) join dependency submition and build

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -1,23 +1,52 @@
-build:
-  runs-on: ubuntu-latest
-  permissions:
-    contents: read
+name: Java CI with Gradle
 
-  steps:
-    - uses: actions/checkout@v4
-    - name: Set up JDK 17
-      uses: actions/setup-java@v4
-      with:
-        java-version: '17'
-        distribution: 'temurin'
+on:
+  push:
+    branches: [ "main" ]
+  pull_request:
+    branches: [ "main" ]
 
-    - name: Setup Gradle
-      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
+jobs:
+  build:
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
 
-    - name: Build with Gradle Wrapper
-      run: |
-        ./gradlew build
-        if [ $? -ne 0 ]; then
-          echo "Error: Gradle build failed."
-          exit 1
-        fi
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
+
+      - name: Build with Gradle Wrapper
+        run: |
+          ./gradlew build
+          if [ $? -ne 0 ]; then
+            echo "Error: Gradle build failed."
+            exit 1
+          fi
+
+  # Si necesitas una acción adicional después de una compilación exitosa, puedes agregarla aquí.
+  # Por ejemplo, una acción para enviar un artefacto generado o notificar sobre el éxito de la compilación.
+
+# Si no se requieren acciones adicionales después de la compilación, puedes eliminar este job.
+# dependency-submission:
+#   runs-on: ubuntu-latest
+#   permissions:
+#     contents: write
+
+#   steps:
+#   - uses: actions/checkout@v4
+#   - name: Set up JDK 17
+#     uses: actions/setup-java@v4
+#     with:
+#       java-version: '17'
+#       distribution: 'temurin'
+
+#   - name: Build with Gradle Wrapper
