(UPDATE) separate verificacion y compilacion

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -9,23 +9,29 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
-    permissions:
-      contents: write
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout código
+        uses: actions/checkout@v2
 
-      - name: Set up JDK 17
-        uses: actions/setup-java@v4
+      - name: Configurar JDK 17
+        uses: actions/setup-java@v2
         with:
           java-version: '17'
           distribution: 'temurin'
 
-      - name: Build with Gradle Wrapper
+      - name: Configurar Gradle
+        uses: gradle/setup-gradle@v3
+
+      - name: Compilar con Gradle Wrapper
+        id: gradle_build
         run: |
-          ./gradlew build
-          if [ $? -ne 0 ]; then
-            echo "Error: Gradle build failed."
-            git reset --hard
-            exit 1
-          fi
+          result=$(./gradlew build 2>&1)  # Ejecutar la compilación y capturar la salida
+          echo "::set-output name=result::${result}"  # Almacenar el resultado en una variable de salida
+
+      - name: Verificar resultado de la compilación
+        if: steps.gradle_build.outputs.result != '0'  # Verificar si la compilación falló (resultado distinto de 0)
+        run: |
+          echo "Error: Gradle build failed."
+          git checkout -- .  # Descartar cambios en el directorio de trabajo
+          exit 1
